[2025-06-09T01:10:11.622+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: deep_models_pipeline.validate_models manual__2025-06-09T01:08:57.902270+00:00 [queued]>
[2025-06-09T01:10:11.629+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: deep_models_pipeline.validate_models manual__2025-06-09T01:08:57.902270+00:00 [queued]>
[2025-06-09T01:10:11.629+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 3
[2025-06-09T01:10:11.639+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): validate_models> on 2025-06-09 01:08:57.902270+00:00
[2025-06-09T01:10:11.645+0000] {standard_task_runner.py:60} INFO - Started process 556 to run task
[2025-06-09T01:10:11.647+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'deep_models_pipeline', 'validate_models', 'manual__2025-06-09T01:08:57.902270+00:00', '--job-id', '3669', '--raw', '--subdir', 'DAGS_FOLDER/train_deep_model_dag.py', '--cfg-path', '/tmp/tmpov7x_qy2']
[2025-06-09T01:10:11.648+0000] {standard_task_runner.py:88} INFO - Job 3669: Subtask validate_models
[2025-06-09T01:10:11.682+0000] {task_command.py:423} INFO - Running <TaskInstance: deep_models_pipeline.validate_models manual__2025-06-09T01:08:57.902270+00:00 [running]> on host 5e3f8e40fa89
[2025-06-09T01:10:11.741+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='deep_models_pipeline' AIRFLOW_CTX_TASK_ID='validate_models' AIRFLOW_CTX_EXECUTION_DATE='2025-06-09T01:08:57.902270+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-06-09T01:08:57.902270+00:00'
[2025-06-09T01:10:11.742+0000] {train_deep_model_dag.py:13} INFO - üü¶ Running command: python /opt/***/src/models/validate_model.py --test_user_count=100
[2025-06-09T01:10:22.375+0000] {train_deep_model_dag.py:20} INFO - üü© [stdout]:

[2025-06-09T01:10:22.376+0000] {train_deep_model_dag.py:22} WARNING - üü® [stderr]:
2025-06-09 01:10:14,803 - INFO - üöÄ Starte Validierung (Deep Hybrid Only)
2025-06-09 01:10:22,052 - ERROR - ‚ùå Fehler beim Laden der Daten/Modelle: No module named 'numpy._core'
Traceback (most recent call last):
  File "/opt/***/src/models/validate_model.py", line 109, in validate_deep_hybrid
    knn_model = pickle.load(open(MODEL_PATH, "rb"))
ModuleNotFoundError: No module named 'numpy._core'

[2025-06-09T01:10:22.377+0000] {python.py:201} INFO - Done. Returned value was: None
[2025-06-09T01:10:22.385+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=deep_models_pipeline, task_id=validate_models, execution_date=20250609T010857, start_date=20250609T011011, end_date=20250609T011022
[2025-06-09T01:10:22.400+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2025-06-09T01:10:22.414+0000] {taskinstance.py:3280} INFO - 1 downstream tasks scheduled from follow-on schedule check
