[2025-06-06T01:29:08.112+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: deep_models_pipeline.train_deep_hybrid_model manual__2025-06-06T01:26:39.800917+00:00 [queued]>
[2025-06-06T01:29:08.121+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: deep_models_pipeline.train_deep_hybrid_model manual__2025-06-06T01:26:39.800917+00:00 [queued]>
[2025-06-06T01:29:08.122+0000] {taskinstance.py:2170} INFO - Starting attempt 2 of 3
[2025-06-06T01:29:08.134+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): train_deep_hybrid_model> on 2025-06-06 01:26:39.800917+00:00
[2025-06-06T01:29:08.142+0000] {standard_task_runner.py:60} INFO - Started process 745 to run task
[2025-06-06T01:29:08.144+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'deep_models_pipeline', 'train_deep_hybrid_model', 'manual__2025-06-06T01:26:39.800917+00:00', '--job-id', '2155', '--raw', '--subdir', 'DAGS_FOLDER/train_deep_model_dag.py', '--cfg-path', '/tmp/tmpb6mk45nf']
[2025-06-06T01:29:08.146+0000] {standard_task_runner.py:88} INFO - Job 2155: Subtask train_deep_hybrid_model
[2025-06-06T01:29:08.188+0000] {task_command.py:423} INFO - Running <TaskInstance: deep_models_pipeline.train_deep_hybrid_model manual__2025-06-06T01:26:39.800917+00:00 [running]> on host b3491b3cd118
[2025-06-06T01:29:08.253+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='deep_models_pipeline' AIRFLOW_CTX_TASK_ID='train_deep_hybrid_model' AIRFLOW_CTX_EXECUTION_DATE='2025-06-06T01:26:39.800917+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-06-06T01:26:39.800917+00:00'
[2025-06-06T01:29:08.255+0000] {train_deep_model_dag.py:13} INFO - üü¶ Running command: python /opt/***/src/models/train_hybrid_deep_model.py --n_neighbors=10 --latent_dim=32
[2025-06-06T01:29:12.679+0000] {train_deep_model_dag.py:20} INFO - üü© [stdout]:

[2025-06-06T01:29:12.680+0000] {train_deep_model_dag.py:22} WARNING - üü® [stderr]:
/home/***/.local/lib/python3.10/site-packages/mlflow/pyfunc/utils/data_validation.py:186: UserWarning: [33mAdd type hints to the `predict` method to enable data validation and automatic signature inference during model logging. Check https://mlflow.org/docs/latest/model/python_model.html#type-hint-usage-in-pythonmodel for more details.[0m
  color_warning(
Traceback (most recent call last):
  File "/opt/***/src/models/train_hybrid_deep_model.py", line 173, in <module>
    train_hybrid_deep_model(
  File "/opt/***/src/models/train_hybrid_deep_model.py", line 60, in train_hybrid_deep_model
    df = pd.read_csv(matrix_path)
  File "/home/***/.local/lib/python3.10/site-packages/pandas/util/_decorators.py", line 211, in wrapper
    return func(*args, **kwargs)
  File "/home/***/.local/lib/python3.10/site-packages/pandas/util/_decorators.py", line 331, in wrapper
    return func(*args, **kwargs)
  File "/home/***/.local/lib/python3.10/site-packages/pandas/io/parsers/readers.py", line 950, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/home/***/.local/lib/python3.10/site-packages/pandas/io/parsers/readers.py", line 605, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/home/***/.local/lib/python3.10/site-packages/pandas/io/parsers/readers.py", line 1442, in __init__
    self._engine = self._make_engine(f, self.engine)
  File "/home/***/.local/lib/python3.10/site-packages/pandas/io/parsers/readers.py", line 1735, in _make_engine
    self.handles = get_handle(
  File "/home/***/.local/lib/python3.10/site-packages/pandas/io/common.py", line 856, in get_handle
    handle = open(
FileNotFoundError: [Errno 2] No such file or directory: '/opt/***/data/processed/hybrid_matrix.csv'

[2025-06-06T01:29:12.680+0000] {train_deep_model_dag.py:29} ERROR - ‚ùå Subprozess-Fehler (exit code 1): python /opt/***/src/models/train_hybrid_deep_model.py --n_neighbors=10 --latent_dim=32
[2025-06-06T01:29:12.680+0000] {train_deep_model_dag.py:32} ERROR - ‚ùå Subprozess-Ausnahme: Command '['python', '/opt/***/src/models/train_hybrid_deep_model.py', '--n_neighbors=10', '--latent_dim=32']' returned non-zero exit status 1.
[2025-06-06T01:29:12.681+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 199, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 216, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/train_deep_model_dag.py", line 103, in run_train_deep_hybrid_model
    run_and_log([
  File "/opt/airflow/dags/train_deep_model_dag.py", line 30, in run_and_log
    raise subprocess.CalledProcessError(result.returncode, command)
subprocess.CalledProcessError: Command '['python', '/opt/airflow/src/models/train_hybrid_deep_model.py', '--n_neighbors=10', '--latent_dim=32']' returned non-zero exit status 1.
[2025-06-06T01:29:12.692+0000] {taskinstance.py:1138} INFO - Marking task as UP_FOR_RETRY. dag_id=deep_models_pipeline, task_id=train_deep_hybrid_model, execution_date=20250606T012639, start_date=20250606T012908, end_date=20250606T012912
[2025-06-06T01:29:12.701+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 2155 for task train_deep_hybrid_model (Command '['python', '/opt/airflow/src/models/train_hybrid_deep_model.py', '--n_neighbors=10', '--latent_dim=32']' returned non-zero exit status 1.; 745)
[2025-06-06T01:29:12.718+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2025-06-06T01:29:12.737+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
