[2025-06-01T11:24:14.094+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: movie_recommendation_pipeline.validate_models manual__2025-06-01T11:18:44.472799+00:00 [queued]>
[2025-06-01T11:24:14.104+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: movie_recommendation_pipeline.validate_models manual__2025-06-01T11:18:44.472799+00:00 [queued]>
[2025-06-01T11:24:14.105+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 3
[2025-06-01T11:24:14.117+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): validate_models> on 2025-06-01 11:18:44.472799+00:00
[2025-06-01T11:24:14.123+0000] {standard_task_runner.py:60} INFO - Started process 555 to run task
[2025-06-01T11:24:14.125+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'movie_recommendation_pipeline', 'validate_models', 'manual__2025-06-01T11:18:44.472799+00:00', '--job-id', '979', '--raw', '--subdir', 'DAGS_FOLDER/mlops_movie_dag.py', '--cfg-path', '/tmp/tmpgwilyfxm']
[2025-06-01T11:24:14.126+0000] {standard_task_runner.py:88} INFO - Job 979: Subtask validate_models
[2025-06-01T11:24:14.158+0000] {task_command.py:423} INFO - Running <TaskInstance: movie_recommendation_pipeline.validate_models manual__2025-06-01T11:18:44.472799+00:00 [running]> on host 754694dd6447
[2025-06-01T11:24:14.214+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='movie_recommendation_pipeline' AIRFLOW_CTX_TASK_ID='validate_models' AIRFLOW_CTX_EXECUTION_DATE='2025-06-01T11:18:44.472799+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-06-01T11:18:44.472799+00:00'
[2025-06-01T11:29:15.847+0000] {mlops_movie_dag.py:13} INFO -                       ❗❗❗ AUTHORIZATION REQUIRED ❗❗❗                      


Open the following link in your browser to authorize the client:
https://dagshub.com/login/oauth/authorize?state=e6b36361-1eac-451d-aacf-eafc3e007006&client_id=32b60ba385aa7cecf24046d8195a71c07dd345d9657977863b52e7748e0f0f28&middleman_request_id=96f3fe335b2f280fbe1872b8de60257577582832755105e008536f0f7a86601a


Traceback (most recent call last):
  File "/opt/***/src/models/validate_model.py", line 17, in <module>
    dagshub.init(repo_owner='sacer11', repo_name='MLOps_movie_rec_apr25', mlflow=True)
  File "/home/***/.local/lib/python3.10/site-packages/dagshub/common/init.py", line 86, in init
    repo_api = RepoAPI(f"{repo_owner}/{repo_name}", host=host)
  File "/home/***/.local/lib/python3.10/site-packages/dagshub/common/api/repo.py", line 78, in __init__
    self.auth = dagshub.auth.get_authenticator(host=host)
  File "/home/***/.local/lib/python3.10/site-packages/dagshub/auth/tokens.py", line 374, in get_authenticator
    return _get_token_storage(**kwargs).get_authenticator(**kwargs)
  File "/home/***/.local/lib/python3.10/site-packages/dagshub/auth/tokens.py", line 122, in get_authenticator
    token = self.get_token_object(host, fail_if_no_token, **kwargs)
  File "/home/***/.local/lib/python3.10/site-packages/dagshub/auth/tokens.py", line 187, in get_token_object
    good_token = oauth.oauth_flow(host, **kwargs)
  File "/home/***/.local/lib/python3.10/site-packages/dagshub/auth/oauth.py", line 46, in oauth_flow
    token = oauth_flow_post(flow_data)
  File "/home/***/.local/lib/python3.10/site-packages/dagshub/auth/oauth.py", line 117, in oauth_flow_post
    raise Exception(f"Error while getting OAuth code: HTTP {res.status_code}, Body: {res.json()}")
  File "/home/***/.local/lib/python3.10/site-packages/httpx/_models.py", line 755, in json
    return jsonlib.loads(self.content.decode(encoding), **kwargs)
  File "/usr/local/lib/python3.10/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python3.10/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/lib/python3.10/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

[2025-06-01T11:29:15.848+0000] {python.py:201} INFO - Done. Returned value was: None
[2025-06-01T11:29:15.856+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=movie_recommendation_pipeline, task_id=validate_models, execution_date=20250601T111844, start_date=20250601T112414, end_date=20250601T112915
[2025-06-01T11:29:15.890+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2025-06-01T11:29:15.912+0000] {taskinstance.py:3280} INFO - 1 downstream tasks scheduled from follow-on schedule check
