[2025-06-02T01:42:04.647+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: movie_recommendation_pipeline.dvc_add_and_push_user manual__2025-06-02T01:35:37.362369+00:00 [queued]>
[2025-06-02T01:42:04.656+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: movie_recommendation_pipeline.dvc_add_and_push_user manual__2025-06-02T01:35:37.362369+00:00 [queued]>
[2025-06-02T01:42:04.656+0000] {taskinstance.py:2170} INFO - Starting attempt 2 of 3
[2025-06-02T01:42:04.667+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): dvc_add_and_push_user> on 2025-06-02 01:35:37.362369+00:00
[2025-06-02T01:42:04.675+0000] {standard_task_runner.py:60} INFO - Started process 1097 to run task
[2025-06-02T01:42:04.676+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'movie_recommendation_pipeline', 'dvc_add_and_push_user', 'manual__2025-06-02T01:35:37.362369+00:00', '--job-id', '1383', '--raw', '--subdir', 'DAGS_FOLDER/mlops_movie_dag.py', '--cfg-path', '/tmp/tmpz3pu9hpl']
[2025-06-02T01:42:04.678+0000] {standard_task_runner.py:88} INFO - Job 1383: Subtask dvc_add_and_push_user
[2025-06-02T01:42:04.710+0000] {task_command.py:423} INFO - Running <TaskInstance: movie_recommendation_pipeline.dvc_add_and_push_user manual__2025-06-02T01:35:37.362369+00:00 [running]> on host b181c6c0b130
[2025-06-02T01:42:04.762+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='movie_recommendation_pipeline' AIRFLOW_CTX_TASK_ID='dvc_add_and_push_user' AIRFLOW_CTX_EXECUTION_DATE='2025-06-02T01:35:37.362369+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-06-02T01:35:37.362369+00:00'
[2025-06-02T01:42:04.763+0000] {mlops_movie_dag.py:12} INFO - üü¶ Running command: dvc add /opt/***/models/user_model.pkl
[2025-06-02T01:42:13.475+0000] {mlops_movie_dag.py:18} INFO - üü© [stdout]:

To track the changes with git, run:

	git add models/user_model.pkl.dvc

To enable auto staging, run:

	dvc config core.autostage true

[2025-06-02T01:42:13.476+0000] {mlops_movie_dag.py:12} INFO - üü¶ Running command: dvc add /opt/***/data/processed/user_matrix.csv
[2025-06-02T01:42:22.627+0000] {mlops_movie_dag.py:18} INFO - üü© [stdout]:

To track the changes with git, run:

	git add data/processed/user_matrix.csv.dvc data/processed/.gitignore

To enable auto staging, run:

	dvc config core.autostage true

[2025-06-02T01:42:22.628+0000] {mlops_movie_dag.py:12} INFO - üü¶ Running command: dvc add /opt/***/data/processed/user_matrix_features.txt
[2025-06-02T01:42:30.422+0000] {mlops_movie_dag.py:18} INFO - üü© [stdout]:

To track the changes with git, run:

	git add data/processed/user_matrix_features.txt.dvc data/processed/.gitignore

To enable auto staging, run:

	dvc config core.autostage true

[2025-06-02T01:42:30.423+0000] {mlops_movie_dag.py:12} INFO - üü¶ Running command: git add /opt/***/models/user_model.pkl.dvc /opt/***/data/processed/user_matrix.csv.dvc /opt/***/data/processed/user_matrix_features.txt.dvc
[2025-06-02T01:42:30.429+0000] {mlops_movie_dag.py:18} INFO - üü© [stdout]:

[2025-06-02T01:42:30.430+0000] {mlops_movie_dag.py:20} WARNING - üü® [stderr]:
fatal: detected dubious ownership in repository at '/opt/***'
To add an exception for this directory, call:

	git config --global --add safe.directory /opt/***

[2025-06-02T01:42:30.431+0000] {mlops_movie_dag.py:22} ERROR - ‚ùå Subprozess-Fehler (exit code 128): git add /opt/***/models/user_model.pkl.dvc /opt/***/data/processed/user_matrix.csv.dvc /opt/***/data/processed/user_matrix_features.txt.dvc
[2025-06-02T01:42:30.431+0000] {mlops_movie_dag.py:25} ERROR - ‚ùå Subprozess-Ausnahme: Command '['git', 'add', '/opt/***/models/user_model.pkl.dvc', '/opt/***/data/processed/user_matrix.csv.dvc', '/opt/***/data/processed/user_matrix_features.txt.dvc']' returned non-zero exit status 128.
[2025-06-02T01:42:30.432+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 199, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 216, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/mlops_movie_dag.py", line 83, in dvc_add_and_push_user
    dvc_add_and_push(artifacts)
  File "/opt/airflow/dags/mlops_movie_dag.py", line 65, in dvc_add_and_push
    run_and_log(["git", "add"] + [a + ".dvc" for a in artifacts])
  File "/opt/airflow/dags/mlops_movie_dag.py", line 23, in run_and_log
    raise subprocess.CalledProcessError(result.returncode, command)
subprocess.CalledProcessError: Command '['git', 'add', '/opt/airflow/models/user_model.pkl.dvc', '/opt/airflow/data/processed/user_matrix.csv.dvc', '/opt/airflow/data/processed/user_matrix_features.txt.dvc']' returned non-zero exit status 128.
[2025-06-02T01:42:30.442+0000] {taskinstance.py:1138} INFO - Marking task as UP_FOR_RETRY. dag_id=movie_recommendation_pipeline, task_id=dvc_add_and_push_user, execution_date=20250602T013537, start_date=20250602T014204, end_date=20250602T014230
[2025-06-02T01:42:30.451+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 1383 for task dvc_add_and_push_user (Command '['git', 'add', '/opt/airflow/models/user_model.pkl.dvc', '/opt/airflow/data/processed/user_matrix.csv.dvc', '/opt/airflow/data/processed/user_matrix_features.txt.dvc']' returned non-zero exit status 128.; 1097)
[2025-06-02T01:42:30.470+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2025-06-02T01:42:30.488+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
