[2025-06-07T22:02:56.777+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: deep_models_pipeline.predict_best_model manual__2025-06-07T22:00:20.103153+00:00 [queued]>
[2025-06-07T22:02:56.786+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: deep_models_pipeline.predict_best_model manual__2025-06-07T22:00:20.103153+00:00 [queued]>
[2025-06-07T22:02:56.787+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 3
[2025-06-07T22:02:56.799+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): predict_best_model> on 2025-06-07 22:00:20.103153+00:00
[2025-06-07T22:02:56.807+0000] {standard_task_runner.py:60} INFO - Started process 711 to run task
[2025-06-07T22:02:56.809+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'deep_models_pipeline', 'predict_best_model', 'manual__2025-06-07T22:00:20.103153+00:00', '--job-id', '2746', '--raw', '--subdir', 'DAGS_FOLDER/train_deep_model_dag.py', '--cfg-path', '/tmp/tmp2srvwm40']
[2025-06-07T22:02:56.811+0000] {standard_task_runner.py:88} INFO - Job 2746: Subtask predict_best_model
[2025-06-07T22:02:56.857+0000] {task_command.py:423} INFO - Running <TaskInstance: deep_models_pipeline.predict_best_model manual__2025-06-07T22:00:20.103153+00:00 [running]> on host e4801a74e885
[2025-06-07T22:02:56.925+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='deep_models_pipeline' AIRFLOW_CTX_TASK_ID='predict_best_model' AIRFLOW_CTX_EXECUTION_DATE='2025-06-07T22:00:20.103153+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-06-07T22:00:20.103153+00:00'
[2025-06-07T22:02:56.926+0000] {train_deep_model_dag.py:13} INFO - üü¶ Running command: python /opt/***/src/models/predict_best_model.py
[2025-06-07T22:03:47.265+0000] {local_task_job_runner.py:302} WARNING - State of this instance has been externally set to failed. Terminating instance.
[2025-06-07T22:03:47.267+0000] {process_utils.py:131} INFO - Sending 15 to group 711. PIDs of all processes in the group: [712, 711]
[2025-06-07T22:03:47.267+0000] {process_utils.py:86} INFO - Sending the signal 15 to group 711
[2025-06-07T22:03:47.268+0000] {taskinstance.py:2450} ERROR - Received SIGTERM. Terminating subprocesses.
[2025-06-07T22:03:47.280+0000] {train_deep_model_dag.py:32} ERROR - ‚ùå Subprozess-Ausnahme: Task received SIGTERM signal
[2025-06-07T22:03:47.320+0000] {process_utils.py:79} INFO - Process psutil.Process(pid=711, status='terminated', exitcode=0, started='22:02:56') (711) terminated with exit code 0
[2025-06-07T22:03:47.321+0000] {process_utils.py:79} INFO - Process psutil.Process(pid=712, status='terminated', started='22:02:56') (712) terminated with exit code None
