[2025-06-07T21:43:28.536+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: deep_models_pipeline.predict_best_model manual__2025-06-07T21:43:27.879449+00:00 [queued]>
[2025-06-07T21:43:28.543+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: deep_models_pipeline.predict_best_model manual__2025-06-07T21:43:27.879449+00:00 [queued]>
[2025-06-07T21:43:28.544+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 3
[2025-06-07T21:43:28.556+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): predict_best_model> on 2025-06-07 21:43:27.879449+00:00
[2025-06-07T21:43:28.562+0000] {standard_task_runner.py:60} INFO - Started process 210 to run task
[2025-06-07T21:43:28.570+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'deep_models_pipeline', 'predict_best_model', 'manual__2025-06-07T21:43:27.879449+00:00', '--job-id', '2661', '--raw', '--subdir', 'DAGS_FOLDER/train_deep_model_dag.py', '--cfg-path', '/tmp/tmp3sv82lw3']
[2025-06-07T21:43:28.573+0000] {standard_task_runner.py:88} INFO - Job 2661: Subtask predict_best_model
[2025-06-07T21:43:28.619+0000] {task_command.py:423} INFO - Running <TaskInstance: deep_models_pipeline.predict_best_model manual__2025-06-07T21:43:27.879449+00:00 [running]> on host 19985e64f4e7
[2025-06-07T21:43:28.695+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='deep_models_pipeline' AIRFLOW_CTX_TASK_ID='predict_best_model' AIRFLOW_CTX_EXECUTION_DATE='2025-06-07T21:43:27.879449+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-06-07T21:43:27.879449+00:00'
[2025-06-07T21:43:28.696+0000] {train_deep_model_dag.py:13} INFO - üü¶ Running command: python /opt/***/src/models/predict_best_model.py
[2025-06-07T21:43:43.716+0000] {local_task_job_runner.py:302} WARNING - State of this instance has been externally set to failed. Terminating instance.
[2025-06-07T21:43:43.719+0000] {process_utils.py:131} INFO - Sending 15 to group 210. PIDs of all processes in the group: [217, 210]
[2025-06-07T21:43:43.720+0000] {process_utils.py:86} INFO - Sending the signal 15 to group 210
[2025-06-07T21:43:43.721+0000] {taskinstance.py:2450} ERROR - Received SIGTERM. Terminating subprocesses.
[2025-06-07T21:43:43.736+0000] {train_deep_model_dag.py:32} ERROR - ‚ùå Subprozess-Ausnahme: Task received SIGTERM signal
[2025-06-07T21:43:43.748+0000] {process_utils.py:79} INFO - Process psutil.Process(pid=217, status='terminated', started='21:43:28') (217) terminated with exit code None
[2025-06-07T21:43:43.762+0000] {process_utils.py:79} INFO - Process psutil.Process(pid=210, status='terminated', exitcode=0, started='21:43:28') (210) terminated with exit code 0
