[2025-06-08T02:40:01.702+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: deep_models_pipeline.train_deep_hybrid_model manual__2025-06-08T02:36:34.410770+00:00 [queued]>
[2025-06-08T02:40:01.716+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: deep_models_pipeline.train_deep_hybrid_model manual__2025-06-08T02:36:34.410770+00:00 [queued]>
[2025-06-08T02:40:01.718+0000] {taskinstance.py:2170} INFO - Starting attempt 2 of 3
[2025-06-08T02:40:01.747+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): train_deep_hybrid_model> on 2025-06-08 02:36:34.410770+00:00
[2025-06-08T02:40:01.792+0000] {standard_task_runner.py:60} INFO - Started process 586 to run task
[2025-06-08T02:40:01.796+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'deep_models_pipeline', 'train_deep_hybrid_model', 'manual__2025-06-08T02:36:34.410770+00:00', '--job-id', '2878', '--raw', '--subdir', 'DAGS_FOLDER/train_deep_model_dag.py', '--cfg-path', '/tmp/tmp_8ozrqu_']
[2025-06-08T02:40:01.802+0000] {standard_task_runner.py:88} INFO - Job 2878: Subtask train_deep_hybrid_model
[2025-06-08T02:40:02.515+0000] {task_command.py:423} INFO - Running <TaskInstance: deep_models_pipeline.train_deep_hybrid_model manual__2025-06-08T02:36:34.410770+00:00 [running]> on host a096f0d31aa8
[2025-06-08T02:40:02.772+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='deep_models_pipeline' AIRFLOW_CTX_TASK_ID='train_deep_hybrid_model' AIRFLOW_CTX_EXECUTION_DATE='2025-06-08T02:36:34.410770+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-06-08T02:36:34.410770+00:00'
[2025-06-08T02:40:02.776+0000] {train_deep_model_dag.py:13} INFO - üü¶ Running command: python /opt/***/src/models/train_hybrid_deep_model.py --n_neighbors=15 --latent_dim=32 --epochs=30 --tfidf_features=300
[2025-06-08T02:42:48.551+0000] {job.py:213} ERROR - Job heartbeat got an exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 3371, in _wrap_pool_connect
    return fn()
  File "/home/airflow/.local/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 327, in connect
    return _ConnectionFairy._checkout(self)
  File "/home/airflow/.local/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 894, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/home/airflow/.local/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 493, in checkout
    rec = pool._do_get()
  File "/home/airflow/.local/lib/python3.10/site-packages/sqlalchemy/pool/impl.py", line 256, in _do_get
    return self._create_connection()
  File "/home/airflow/.local/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 273, in _create_connection
    return _ConnectionRecord(self)
  File "/home/airflow/.local/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 388, in __init__
    self.__connect()
  File "/home/airflow/.local/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 690, in __connect
    with util.safe_reraise():
  File "/home/airflow/.local/lib/python3.10/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/home/airflow/.local/lib/python3.10/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 686, in __connect
    self.dbapi_connection = connection = pool._invoke_creator(self)
  File "/home/airflow/.local/lib/python3.10/site-packages/sqlalchemy/engine/create.py", line 574, in connect
    return dialect.connect(*cargs, **cparams)
  File "/home/airflow/.local/lib/python3.10/site-packages/sqlalchemy/engine/default.py", line 598, in connect
    return self.dbapi.connect(*cargs, **cparams)
  File "/home/airflow/.local/lib/python3.10/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: could not translate host name "postgres" to address: Temporary failure in name resolution


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/jobs/job.py", line 187, in heartbeat
    self._merge_from(Job._fetch_from_db(self, session))
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/api_internal/internal_api_call.py", line 114, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/session.py", line 76, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/jobs/job.py", line 308, in _fetch_from_db
    session.merge(job)
  File "/home/airflow/.local/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 3056, in merge
    return self._merge(
  File "/home/airflow/.local/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 3136, in _merge
    merged = self.get(
  File "/home/airflow/.local/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 2853, in get
    return self._get_impl(
  File "/home/airflow/.local/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 2975, in _get_impl
    return db_load_fn(
  File "/home/airflow/.local/lib/python3.10/site-packages/sqlalchemy/orm/loading.py", line 530, in load_on_pk_identity
    session.execute(
  File "/home/airflow/.local/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 1716, in execute
    conn = self._connection_for_bind(bind)
  File "/home/airflow/.local/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 1555, in _connection_for_bind
    return self._transaction._connection_for_bind(
  File "/home/airflow/.local/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 750, in _connection_for_bind
    conn = bind.connect()
  File "/home/airflow/.local/lib/python3.10/site-packages/sqlalchemy/future/engine.py", line 412, in connect
    return super(Engine, self).connect()
  File "/home/airflow/.local/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 3325, in connect
    return self._connection_cls(self, close_with_result=close_with_result)
  File "/home/airflow/.local/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 96, in __init__
    else engine.raw_connection()
  File "/home/airflow/.local/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 3404, in raw_connection
    return self._wrap_pool_connect(self.pool.connect, _connection)
  File "/home/airflow/.local/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 3374, in _wrap_pool_connect
    Connection._handle_dbapi_exception_noconnection(
  File "/home/airflow/.local/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 2208, in _handle_dbapi_exception_noconnection
    util.raise_(
  File "/home/airflow/.local/lib/python3.10/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 3371, in _wrap_pool_connect
    return fn()
  File "/home/airflow/.local/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 327, in connect
    return _ConnectionFairy._checkout(self)
  File "/home/airflow/.local/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 894, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/home/airflow/.local/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 493, in checkout
    rec = pool._do_get()
  File "/home/airflow/.local/lib/python3.10/site-packages/sqlalchemy/pool/impl.py", line 256, in _do_get
    return self._create_connection()
  File "/home/airflow/.local/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 273, in _create_connection
    return _ConnectionRecord(self)
  File "/home/airflow/.local/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 388, in __init__
    self.__connect()
  File "/home/airflow/.local/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 690, in __connect
    with util.safe_reraise():
  File "/home/airflow/.local/lib/python3.10/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/home/airflow/.local/lib/python3.10/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 686, in __connect
    self.dbapi_connection = connection = pool._invoke_creator(self)
  File "/home/airflow/.local/lib/python3.10/site-packages/sqlalchemy/engine/create.py", line 574, in connect
    return dialect.connect(*cargs, **cparams)
  File "/home/airflow/.local/lib/python3.10/site-packages/sqlalchemy/engine/default.py", line 598, in connect
    return self.dbapi.connect(*cargs, **cparams)
  File "/home/airflow/.local/lib/python3.10/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
sqlalchemy.exc.OperationalError: (psycopg2.OperationalError) could not translate host name "postgres" to address: Temporary failure in name resolution

(Background on this error at: https://sqlalche.me/e/14/e3q8)
[2025-06-08T02:42:48.625+0000] {job.py:221} ERROR - Job heartbeat failed with error. Scheduler is in unhealthy state
[2025-06-08T02:46:49.694+0000] {train_deep_model_dag.py:20} INFO - üü© [stdout]:
üèÉ View run train_hybrid_deep_model at: https://dagshub.com/sacer11/MLOps_movie_rec_apr25.mlflow/#/experiments/10/runs/95f9b94dd3ff4ecb8395838e1df3c317
üß™ View experiment at: https://dagshub.com/sacer11/MLOps_movie_rec_apr25.mlflow/#/experiments/10

[2025-06-08T02:46:49.734+0000] {train_deep_model_dag.py:22} WARNING - üü® [stderr]:
2025-06-08 02:40:55,244 - __main__ - INFO - üì• Lade Rohdaten und baue Hybrid-Feature-Matrix ...
2025-06-08 02:43:56,642 - __main__ - INFO - üìê Hybrid-Matrix erstellt mit Shape: (10381, 1429), Feature-Namen: 1429
2025-06-08 02:44:14,627 - __main__ - INFO - üíæ Hybrid-Matrix gespeichert unter /opt/***/data/processed/hybrid_matrix.csv
2025-06-08 02:44:14,719 - __main__ - INFO - üöÄ Starte Training Autoencoder ...
2025-06-08 02:44:26,750 - __main__ - INFO - Epoch 1/30: Loss = 0.0122
2025-06-08 02:44:42,153 - __main__ - INFO - Epoch 2/30: Loss = 0.0072
2025-06-08 02:44:54,345 - __main__ - INFO - Epoch 3/30: Loss = 0.0062
2025-06-08 02:44:59,598 - __main__ - INFO - Epoch 4/30: Loss = 0.0058
2025-06-08 02:45:02,398 - __main__ - INFO - Epoch 5/30: Loss = 0.0055
2025-06-08 02:45:05,169 - __main__ - INFO - Epoch 6/30: Loss = 0.0053
2025-06-08 02:45:09,148 - __main__ - INFO - Epoch 7/30: Loss = 0.0052
2025-06-08 02:45:11,326 - __main__ - INFO - Epoch 8/30: Loss = 0.0051
2025-06-08 02:45:13,977 - __main__ - INFO - Epoch 9/30: Loss = 0.0050
2025-06-08 02:45:17,043 - __main__ - INFO - Epoch 10/30: Loss = 0.0049
2025-06-08 02:45:19,586 - __main__ - INFO - Epoch 11/30: Loss = 0.0048
2025-06-08 02:45:22,336 - __main__ - INFO - Epoch 12/30: Loss = 0.0048
2025-06-08 02:45:24,694 - __main__ - INFO - Epoch 13/30: Loss = 0.0047
2025-06-08 02:45:27,358 - __main__ - INFO - Epoch 14/30: Loss = 0.0047
2025-06-08 02:45:29,734 - __main__ - INFO - Epoch 15/30: Loss = 0.0047
2025-06-08 02:45:32,192 - __main__ - INFO - Epoch 16/30: Loss = 0.0046
2025-06-08 02:45:34,276 - __main__ - INFO - Epoch 17/30: Loss = 0.0046
2025-06-08 02:45:37,936 - __main__ - INFO - Epoch 18/30: Loss = 0.0046
2025-06-08 02:45:41,716 - __main__ - INFO - Epoch 19/30: Loss = 0.0045
2025-06-08 02:45:44,175 - __main__ - INFO - Epoch 20/30: Loss = 0.0045
2025-06-08 02:45:46,724 - __main__ - INFO - Epoch 21/30: Loss = 0.0045
2025-06-08 02:45:50,064 - __main__ - INFO - Epoch 22/30: Loss = 0.0045
2025-06-08 02:45:54,245 - __main__ - INFO - Epoch 23/30: Loss = 0.0045
2025-06-08 02:45:59,537 - __main__ - INFO - Epoch 24/30: Loss = 0.0045
2025-06-08 02:46:02,763 - __main__ - INFO - Epoch 25/30: Loss = 0.0044
2025-06-08 02:46:05,623 - __main__ - INFO - Epoch 26/30: Loss = 0.0044
2025-06-08 02:46:07,990 - __main__ - INFO - Epoch 27/30: Loss = 0.0044
2025-06-08 02:46:10,438 - __main__ - INFO - Epoch 28/30: Loss = 0.0044
2025-06-08 02:46:13,144 - __main__ - INFO - Epoch 29/30: Loss = 0.0044
2025-06-08 02:46:15,913 - __main__ - INFO - Epoch 30/30: Loss = 0.0044
2025-06-08 02:46:16,418 - __main__ - INFO - ‚úÖ Hybrid-Embeddings gespeichert unter /opt/***/data/processed/hybrid_deep_embedding.csv
2025-06-08 02:46:16,419 - __main__ - INFO - ‚úÖ Hybrid-Embeddings gespeichert unter /opt/***/data/processed/hybrid_deep_embedding.csv
2025-06-08 02:46:16,431 - __main__ - INFO - ‚úÖ Deep KNN Modell gespeichert unter /opt/***/models/hybrid_deep_knn.pkl
2025/06/08 02:46:21 INFO mlflow.pyfunc: Validating input example against model signature

Downloading artifacts:   0%|          | 0/1 [00:00<?, ?it/s]
Downloading artifacts: 100%|‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà| 1/1 [00:00<00:00, 94.58it/s]
Downloading artifacts: 100%|‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà| 1/1 [00:00<00:00, 92.19it/s]
Registered model 'hybrid_deep_model' already exists. Creating a new version of this model...
2025/06/08 02:46:37 INFO mlflow.store.model_registry.abstract_store: Waiting up to 300 seconds for model version to finish creation. Model name: hybrid_deep_model, version 30
Created version '30' of model 'hybrid_deep_model'.
2025-06-08 02:46:44,869 - __main__ - INFO - üìù Tags f√ºr Modellversion 30 gesetzt: n_neighbors=15, latent_dim=32, tfidf_features=300, epochs=30
2025-06-08 02:46:47,012 - __main__ - INFO - üèÅ Deep Hybrid-Model Training abgeschlossen und geloggt.

[2025-06-08T02:46:49.749+0000] {python.py:201} INFO - Done. Returned value was: None
[2025-06-08T02:46:50.074+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=deep_models_pipeline, task_id=train_deep_hybrid_model, execution_date=20250608T023634, start_date=20250608T024001, end_date=20250608T024650
[2025-06-08T02:46:50.284+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2025-06-08T02:46:50.380+0000] {taskinstance.py:3280} INFO - 1 downstream tasks scheduled from follow-on schedule check
