[2025-06-07T21:57:54.516+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: deep_models_pipeline.predict_best_model manual__2025-06-07T21:57:53.116793+00:00 [queued]>
[2025-06-07T21:57:54.526+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: deep_models_pipeline.predict_best_model manual__2025-06-07T21:57:53.116793+00:00 [queued]>
[2025-06-07T21:57:54.526+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 3
[2025-06-07T21:57:54.540+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): predict_best_model> on 2025-06-07 21:57:53.116793+00:00
[2025-06-07T21:57:54.547+0000] {standard_task_runner.py:60} INFO - Started process 980 to run task
[2025-06-07T21:57:54.549+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'deep_models_pipeline', 'predict_best_model', 'manual__2025-06-07T21:57:53.116793+00:00', '--job-id', '2703', '--raw', '--subdir', 'DAGS_FOLDER/train_deep_model_dag.py', '--cfg-path', '/tmp/tmpufxqx6g1']
[2025-06-07T21:57:54.551+0000] {standard_task_runner.py:88} INFO - Job 2703: Subtask predict_best_model
[2025-06-07T21:57:54.609+0000] {task_command.py:423} INFO - Running <TaskInstance: deep_models_pipeline.predict_best_model manual__2025-06-07T21:57:53.116793+00:00 [running]> on host a47caab93d5d
[2025-06-07T21:57:54.747+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='deep_models_pipeline' AIRFLOW_CTX_TASK_ID='predict_best_model' AIRFLOW_CTX_EXECUTION_DATE='2025-06-07T21:57:53.116793+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-06-07T21:57:53.116793+00:00'
[2025-06-07T21:57:54.748+0000] {train_deep_model_dag.py:13} INFO - üü¶ Running command: python /opt/***/src/models/predict_best_model.py
[2025-06-07T21:58:14.796+0000] {local_task_job_runner.py:302} WARNING - State of this instance has been externally set to failed. Terminating instance.
[2025-06-07T21:58:14.801+0000] {process_utils.py:131} INFO - Sending 15 to group 980. PIDs of all processes in the group: [984, 980]
[2025-06-07T21:58:14.801+0000] {process_utils.py:86} INFO - Sending the signal 15 to group 980
[2025-06-07T21:58:14.804+0000] {taskinstance.py:2450} ERROR - Received SIGTERM. Terminating subprocesses.
[2025-06-07T21:58:14.817+0000] {train_deep_model_dag.py:32} ERROR - ‚ùå Subprozess-Ausnahme: Task received SIGTERM signal
[2025-06-07T21:58:14.857+0000] {process_utils.py:79} INFO - Process psutil.Process(pid=980, status='terminated', exitcode=0, started='21:57:54') (980) terminated with exit code 0
[2025-06-07T21:58:14.858+0000] {process_utils.py:79} INFO - Process psutil.Process(pid=984, status='terminated', started='21:57:54') (984) terminated with exit code None
