[2025-06-05T21:17:28.753+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: deep_models_pipeline.dvc_pull_bestmodels manual__2025-06-05T21:15:55.562459+00:00 [queued]>
[2025-06-05T21:17:28.760+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: deep_models_pipeline.dvc_pull_bestmodels manual__2025-06-05T21:15:55.562459+00:00 [queued]>
[2025-06-05T21:17:28.761+0000] {taskinstance.py:2170} INFO - Starting attempt 2 of 3
[2025-06-05T21:17:28.770+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): dvc_pull_bestmodels> on 2025-06-05 21:15:55.562459+00:00
[2025-06-05T21:17:28.776+0000] {standard_task_runner.py:60} INFO - Started process 4520 to run task
[2025-06-05T21:17:28.778+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'deep_models_pipeline', 'dvc_pull_bestmodels', 'manual__2025-06-05T21:15:55.562459+00:00', '--job-id', '2022', '--raw', '--subdir', 'DAGS_FOLDER/train_deep_model_dag.py', '--cfg-path', '/tmp/tmpoc1bhx83']
[2025-06-05T21:17:28.779+0000] {standard_task_runner.py:88} INFO - Job 2022: Subtask dvc_pull_bestmodels
[2025-06-05T21:17:28.813+0000] {task_command.py:423} INFO - Running <TaskInstance: deep_models_pipeline.dvc_pull_bestmodels manual__2025-06-05T21:15:55.562459+00:00 [running]> on host 3f2696f940ac
[2025-06-05T21:17:28.872+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='deep_models_pipeline' AIRFLOW_CTX_TASK_ID='dvc_pull_bestmodels' AIRFLOW_CTX_EXECUTION_DATE='2025-06-05T21:15:55.562459+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-06-05T21:15:55.562459+00:00'
[2025-06-05T21:17:28.873+0000] {train_deep_model_dag.py:13} INFO - üü¶ Running command: dvc pull /opt/***/models/hybrid_deep_model.pkl
[2025-06-05T21:17:44.221+0000] {train_deep_model_dag.py:20} INFO - üü© [stdout]:

[2025-06-05T21:17:44.222+0000] {train_deep_model_dag.py:22} WARNING - üü® [stderr]:
WARNING: failed to collect 'workspace', skipping
ERROR: failed to pull data from the cloud - '/opt/***/models/hybrid_deep_model.pkl' does not exist as an output or a stage name in 'dvc.yaml': 'dvc.yaml' does not exist

[2025-06-05T21:17:44.222+0000] {train_deep_model_dag.py:29} ERROR - ‚ùå Subprozess-Fehler (exit code 1): dvc pull /opt/***/models/hybrid_deep_model.pkl
[2025-06-05T21:17:44.223+0000] {train_deep_model_dag.py:32} ERROR - ‚ùå Subprozess-Ausnahme: Command '['dvc', 'pull', '/opt/***/models/hybrid_deep_model.pkl']' returned non-zero exit status 1.
[2025-06-05T21:17:44.223+0000] {train_deep_model_dag.py:84} ERROR - ‚ùå Unerwarteter Fehler beim DVC-Pull f√ºr /opt/***/models/hybrid_deep_model.pkl: Command '['dvc', 'pull', '/opt/***/models/hybrid_deep_model.pkl']' returned non-zero exit status 1.
[2025-06-05T21:17:44.224+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 199, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 216, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/train_deep_model_dag.py", line 74, in dvc_pull_bestmodels_dl
    run_and_log(["dvc", "pull", art])
  File "/opt/airflow/dags/train_deep_model_dag.py", line 30, in run_and_log
    raise subprocess.CalledProcessError(result.returncode, command)
subprocess.CalledProcessError: Command '['dvc', 'pull', '/opt/airflow/models/hybrid_deep_model.pkl']' returned non-zero exit status 1.
[2025-06-05T21:17:44.235+0000] {taskinstance.py:1138} INFO - Marking task as UP_FOR_RETRY. dag_id=deep_models_pipeline, task_id=dvc_pull_bestmodels, execution_date=20250605T211555, start_date=20250605T211728, end_date=20250605T211744
[2025-06-05T21:17:44.246+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 2022 for task dvc_pull_bestmodels (Command '['dvc', 'pull', '/opt/airflow/models/hybrid_deep_model.pkl']' returned non-zero exit status 1.; 4520)
[2025-06-05T21:17:44.291+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2025-06-05T21:17:44.306+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
