[2025-06-18T12:00:00.364+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: drift_monitoring_dag.generate_embedding_snapshot scheduled__2025-06-18T11:00:00+00:00 [queued]>
[2025-06-18T12:00:00.371+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: drift_monitoring_dag.generate_embedding_snapshot scheduled__2025-06-18T11:00:00+00:00 [queued]>
[2025-06-18T12:00:00.372+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 2
[2025-06-18T12:00:00.383+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): generate_embedding_snapshot> on 2025-06-18 11:00:00+00:00
[2025-06-18T12:00:00.392+0000] {standard_task_runner.py:60} INFO - Started process 478 to run task
[2025-06-18T12:00:00.394+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'drift_monitoring_dag', 'generate_embedding_snapshot', 'scheduled__2025-06-18T11:00:00+00:00', '--job-id', '565', '--raw', '--subdir', 'DAGS_FOLDER/drift_monitoring_dag.py', '--cfg-path', '/tmp/tmpd262i3tm']
[2025-06-18T12:00:00.396+0000] {standard_task_runner.py:88} INFO - Job 565: Subtask generate_embedding_snapshot
[2025-06-18T12:00:00.440+0000] {task_command.py:423} INFO - Running <TaskInstance: drift_monitoring_dag.generate_embedding_snapshot scheduled__2025-06-18T11:00:00+00:00 [running]> on host b50ef10c1330
[2025-06-18T12:00:00.519+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='drift_monitoring_dag' AIRFLOW_CTX_TASK_ID='generate_embedding_snapshot' AIRFLOW_CTX_EXECUTION_DATE='2025-06-18T11:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-06-18T11:00:00+00:00'
[2025-06-18T12:00:00.521+0000] {drift_monitoring_dag.py:48} INFO - üß¨ Generate Snapshot-Embedding...
[2025-06-18T12:00:01.164+0000] {drift_monitoring_dag.py:55} INFO - ‚úÖ Embedding-Snapshot with code 1
[2025-06-18T12:00:01.165+0000] {drift_monitoring_dag.py:59} WARNING - [2025-06-18 12:00:01,086] ERROR - ‚ùå Error loading embedding: [Errno 2] No such file or directory: '/opt/***/data/processed/hybrid_deep_embedding.csv'
Traceback (most recent call last):
  File "/opt/***/src/monitoring/generate_embedding.py", line 21, in <module>
    embedding_df = pd.read_csv(embedding_path, index_col=0)
  File "/home/***/.local/lib/python3.10/site-packages/pandas/io/parsers/readers.py", line 1026, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/home/***/.local/lib/python3.10/site-packages/pandas/io/parsers/readers.py", line 620, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/home/***/.local/lib/python3.10/site-packages/pandas/io/parsers/readers.py", line 1620, in __init__
    self._engine = self._make_engine(f, self.engine)
  File "/home/***/.local/lib/python3.10/site-packages/pandas/io/parsers/readers.py", line 1880, in _make_engine
    self.handles = get_handle(
  File "/home/***/.local/lib/python3.10/site-packages/pandas/io/common.py", line 873, in get_handle
    handle = open(
FileNotFoundError: [Errno 2] No such file or directory: '/opt/***/data/processed/hybrid_deep_embedding.csv'

[2025-06-18T12:00:01.166+0000] {python.py:201} INFO - Done. Returned value was: None
[2025-06-18T12:00:01.174+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=drift_monitoring_dag, task_id=generate_embedding_snapshot, execution_date=20250618T110000, start_date=20250618T120000, end_date=20250618T120001
[2025-06-18T12:00:01.210+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2025-06-18T12:00:01.235+0000] {taskinstance.py:3280} INFO - 1 downstream tasks scheduled from follow-on schedule check
