[2025-06-02T00:38:24.744+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: movie_recommendation_pipeline.validate_models manual__2025-06-02T00:34:18.343703+00:00 [queued]>
[2025-06-02T00:38:24.752+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: movie_recommendation_pipeline.validate_models manual__2025-06-02T00:34:18.343703+00:00 [queued]>
[2025-06-02T00:38:24.752+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 3
[2025-06-02T00:38:24.763+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): validate_models> on 2025-06-02 00:34:18.343703+00:00
[2025-06-02T00:38:24.771+0000] {standard_task_runner.py:60} INFO - Started process 723 to run task
[2025-06-02T00:38:24.773+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'movie_recommendation_pipeline', 'validate_models', 'manual__2025-06-02T00:34:18.343703+00:00', '--job-id', '1348', '--raw', '--subdir', 'DAGS_FOLDER/mlops_movie_dag.py', '--cfg-path', '/tmp/tmps5udy9dw']
[2025-06-02T00:38:24.774+0000] {standard_task_runner.py:88} INFO - Job 1348: Subtask validate_models
[2025-06-02T00:38:24.810+0000] {task_command.py:423} INFO - Running <TaskInstance: movie_recommendation_pipeline.validate_models manual__2025-06-02T00:34:18.343703+00:00 [running]> on host 8771dc7bcee3
[2025-06-02T00:38:24.872+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='movie_recommendation_pipeline' AIRFLOW_CTX_TASK_ID='validate_models' AIRFLOW_CTX_EXECUTION_DATE='2025-06-02T00:34:18.343703+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-06-02T00:34:18.343703+00:00'
[2025-06-02T00:38:24.874+0000] {mlops_movie_dag.py:12} INFO - üü¶ Running command: python /opt/***/src/models/validate_model.py
[2025-06-02T00:38:34.262+0000] {mlops_movie_dag.py:18} INFO - üü© [stdout]:

[2025-06-02T00:38:34.262+0000] {mlops_movie_dag.py:20} WARNING - üü® [stderr]:
2025-06-02 00:38:26,678 - INFO - üöÄ Starte Validierung der Modelle
WARNING: failed to collect 'workspace', skipping
ERROR: failed to pull data from the cloud - '/opt/***/models/hybrid_model.pkl.dvc' is not a .dvc file
2025-06-02 00:38:33,971 - ERROR - ‚ùå Fehler bei DVC Pull f√ºr /opt/***/models/hybrid_model.pkl: Command '['dvc', 'pull', '/opt/***/models/hybrid_model.pkl']' returned non-zero exit status 1.
2025-06-02 00:38:33,971 - ERROR - ‚ùå Konnte Modelle nicht von DVC holen!

[2025-06-02T00:38:34.263+0000] {python.py:201} INFO - Done. Returned value was: None
[2025-06-02T00:38:34.271+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=movie_recommendation_pipeline, task_id=validate_models, execution_date=20250602T003418, start_date=20250602T003824, end_date=20250602T003834
[2025-06-02T00:38:34.287+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2025-06-02T00:38:34.301+0000] {taskinstance.py:3280} INFO - 1 downstream tasks scheduled from follow-on schedule check
